### ISSUE TITLE
Error when excuting doctrine:schema:update

### ISSUE THREAD

**Issue by daifma** [boldtrn/JsonbBundle#10]
Hi I create my entitiy with jsonb field.
When I excute doctrine:schema:update --force I get the following error
`  [Doctrine\DBAL\DBALException]                                                                                                                                                                                                    
  Unknown column type "jsonb" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap().   
  If this error occurs during database introspection then you might have forgot to register all database types for a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#g  
  etMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping information. `

**Comment by boldtrn** [comment]
Thanks for reporting. Have you followed the setup described in the REAMDE? The config is adding the type jsonb to the types. Please make sure you followed the instructions, if the error persists, the structure of Symfony changed eventually?

**Comment by boldtrn** [comment]
Will close this stale issue
