### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by dunglas** [boldtrn/JsonbBundle#15]
Hi, and thanks for this bundle!

According to the `composer.json` file, this project is under the MIT license, but the `LICENSE` file is missing (so GitHub cannot detect the license).

**Comment by boldtrn** [comment]
Thanks, I added a LICENSE file in: https://github.com/boldtrn/JsonbBundle/commit/0316476c8baa2267ab301d9a2821a98626a3b978
